# Generated by Django 5.0 on 2024-09-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_model',
            options={'ordering': ['-batch', 'std_id'], 'verbose_name': 'Student Info'},
        ),
    ]
