# Generated by Django 5.0 on 2024-09-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_model_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='batch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
