# Generated by Django 5.0 on 2024-09-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_model_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='skills',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
