# Generated by Django 5.0 on 2024-09-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_model_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
