# Generated by Django 5.0 on 2024-09-20 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_model_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='students_certificates')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.student_model')),
            ],
            options={
                'verbose_name_plural': 'Students Certificates',
                'ordering': ['profile__batch', 'profile__std_id', '-upload_date'],
            },
        ),
    ]
