# Generated by Django 5.0 on 2024-09-26 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_certificate_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate_photo',
            options={'ordering': ['profile__batch', 'profile__std_id', '-upload_date'], 'verbose_name_plural': 'Student Certificates'},
        ),
        migrations.CreateModel(
            name='Thumbnail_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='thumbnails')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='students.student_model')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
