# Generated by Django 5.0 on 2024-09-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_certificate_photo_options_thumbnail_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='passion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
