# Generated by Django 5.0 on 2024-10-01 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_rename_passion_student_model_passions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_model',
            old_name='passions',
            new_name='passion',
        ),
    ]
