# Generated by Django 5.0 on 2024-10-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_student_model_blood_group_student_model_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='blood_group',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
