# Generated by Django 5.0 on 2024-10-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_student_model_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='last_donated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
