# Generated by Django 5.0 on 2024-10-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_student_model_last_donated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_model',
            old_name='last_donated',
            new_name='last_Blood_donated',
        ),
    ]
