# Generated by Django 5.0 on 2024-10-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_rename_last_donated_student_model_last_blood_donated'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_model',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_model',
            name='google_scholar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_model',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_model',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
