# Generated by Django 5.0 on 2024-10-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_student_model_facebook_student_model_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='gmail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
