# Generated by Django 5.0 on 2024-10-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_student_model_gmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
