# Generated by Django 5.0 on 2024-10-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_alter_student_model_gmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
