# Generated by Django 5.0 on 2024-09-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
