# Generated by Django 5.0 on 2024-09-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0002_alter_notice_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
    ]
