# Generated by Django 5.0 on 2024-09-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0005_alter_notice_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='file',
            new_name='pdf',
        ),
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notice_image'),
        ),
    ]
