# Generated by Django 5.0 on 2024-09-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0010_remove_routine_pdf_routine_routine_pdf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Routine',
            new_name='RoutineModel',
        ),
    ]
