# Generated by Django 5.0 on 2024-09-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0011_rename_routine_routinemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routinemodel',
            options={'ordering': ['update_date'], 'verbose_name': 'Update previous routine'},
        ),
    ]
