# Generated by Django 5.0 on 2024-09-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0012_alter_routinemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='slug',
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
