# Generated by Django 5.0 on 2024-09-26 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0013_alter_notice_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notice_image')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='noticeapp.notice')),
            ],
            options={
                'ordering': ['notice', 'pk'],
            },
        ),
    ]
