# Generated by Django 5.0 on 2024-09-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0014_notice_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_images',
            name='image',
            field=models.ImageField(default=None, upload_to='notice_image'),
            preserve_default=False,
        ),
    ]
