# Generated by Django 5.0 on 2024-09-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0015_alter_notice_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='image',
        ),
    ]
