# Generated by Django 5.1.1 on 2024-10-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0019_alter_routinemodel_routine_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routinemodel',
            name='routine_photo',
            field=models.ImageField(blank=True, null=True, upload_to='routine_photo', verbose_name='Routine photo'),
        ),
    ]
