# Generated by Django 5.1.1 on 2024-10-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0020_alter_routinemodel_routine_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routinemodel',
            name='routine_photo',
            field=models.ImageField(help_text="To convert the pdf into jpg visit https://smallpdf.com/pdf-converter or <a href='https://smallpdf.com/pdf-converter' target='_blank'><span style='color:green;font-size:20px;'>click here</span></a>", upload_to='routine_photo', verbose_name='Routine photo'),
        ),
    ]
