# Generated by Django 5.1.1 on 2024-10-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0021_alter_routinemodel_routine_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routinemodel',
            options={'verbose_name': 'Update previous routine'},
        ),
    ]
