# Generated by Django 5.0 on 2024-09-05 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carosel',
            new_name='Carousel',
        ),
    ]
