# Generated by Django 5.0 on 2024-09-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0004_activity_gallery_galleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity_gallery',
            options={'verbose_name_plural': 'Activity Gallery'},
        ),
        migrations.AddField(
            model_name='activity_gallery',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
