# Generated by Django 5.0 on 2024-09-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0006_alter_activity_gallery_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity_gallery',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Activity Gallery'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['gallery']},
        ),
    ]
