# Generated by Django 5.1.1 on 2024-10-22 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0007_alter_activity_gallery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Activity_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='activity_gallery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='galleryapp.category_activity_gallery'),
        ),
    ]
