# Generated by Django 5.0 on 2024-10-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_profile',
            name='academic_info',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='experience',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='publications',
            field=models.JSONField(default=list, null=True),
        ),
    ]
