# Generated by Django 5.0 on 2024-10-03 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_profile',
            name='academic_info',
        ),
        migrations.RemoveField(
            model_name='faculty_profile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='faculty_profile',
            name='publications',
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='designation',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_members'),
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='research_interest',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='short_biography',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='sorting_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Academic_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=60)),
                ('institution', models.CharField(max_length=60)),
                ('period', models.CharField(max_length=60)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_info', to='Faculty_app.faculty_profile')),
            ],
            options={
                'ordering': ['faculty__name', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_organization', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=60)),
                ('job_role', models.CharField(max_length=60)),
                ('period', models.CharField(max_length=60)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='Faculty_app.faculty_profile')),
            ],
            options={
                'ordering': ['faculty__name', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Research_and_publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_and_publication', models.TextField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_and_publications', to='Faculty_app.faculty_profile')),
            ],
            options={
                'ordering': ['faculty__name'],
            },
        ),
    ]
