# Generated by Django 5.0 on 2024-10-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty_app', '0002_alter_faculty_profile_academic_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_profile',
            name='academic_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='experience',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='publications',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
