# Generated by Django 5.0 on 2024-10-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty_app', '0002_remove_faculty_profile_academic_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_profile',
            name='github',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
