# Generated by Django 5.0 on 2024-10-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty_app', '0003_faculty_profile_github_faculty_profile_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_profile',
            name='research_interest',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='short_biography',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
