# Generated by Django 5.0 on 2024-10-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty_app', '0003_alter_faculty_profile_academic_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_profile',
            name='designation',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_members'),
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='research_interest',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='short_biography',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
