# Generated by Django 5.0 on 2024-10-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty_app', '0004_faculty_profile_designation_faculty_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_profile',
            name='sorting_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
