# Generated by Django 5.0 on 2024-10-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty_app', '0004_alter_faculty_profile_research_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_info',
            name='period',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_role',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='period',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
