# Generated by Django 5.0 on 2024-10-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty_app', '0005_faculty_profile_sorting_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_profile',
            name='academic_info',
        ),
        migrations.RemoveField(
            model_name='faculty_profile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='faculty_profile',
            name='publications',
        ),
    ]
