# Generated by Django 5.0 on 2024-10-02 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty_app', '0006_remove_faculty_profile_academic_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research_and_publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_and_publications', to='Faculty_app.faculty_profile')),
            ],
        ),
    ]
