# Generated by Django 5.0 on 2024-10-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty_app', '0006_faculty_staff_alter_faculty_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_info',
            name='degree',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='academic_info',
            name='institution',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_role',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(max_length=220),
        ),
    ]
