# Generated by Django 5.0 on 2024-10-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty_app', '0007_research_and_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research_and_publication',
            old_name='data',
            new_name='research_and_publication',
        ),
    ]
