# Generated by Django 5.0 on 2024-10-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty_app', '0008_instructor_developer_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor_developer_moderator',
            name='facebook',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
