# Generated by Django 5.0 on 2024-10-02 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty_app', '0009_academic_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_organization', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=60)),
                ('job_role', models.CharField(max_length=60)),
                ('period', models.CharField(max_length=60)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='Faculty_app.faculty_profile')),
            ],
        ),
    ]
