# Generated by Django 5.0 on 2024-10-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty_app', '0009_instructor_developer_moderator_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor_developer_moderator',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='inst_dev_moder'),
        ),
    ]
