# Generated by Django 5.1.1 on 2024-10-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty_app', '0010_alter_instructor_developer_moderator_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_CSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=200, null=True)),
                ('body1', models.CharField(blank=True, max_length=2000, null=True)),
                ('title2', models.CharField(blank=True, max_length=200, null=True)),
                ('body2', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
