# Generated by Django 5.1.1 on 2024-10-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty_app', '0012_alter_about_cse_options_alter_about_cse_body1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_profile',
            name='department_head',
            field=models.BooleanField(default=False),
        ),
    ]
